/*
 * JML specification Copyright 2004 SoS Group, University of Nijmegen
 * Modified 2007, Systems Research Group, University College Dublin
 */

package sos.koa;

import java.io.File;
import java.util.Properties;

/**
 * Global constants used in the user interface.
 *
 * @version $Id$
 *
 * @author Engelbert Hubbers (hubbers@cs.kun.nl)
 */
public /*@ nullable_by_default @*/ interface KOAConstants {

   // Release info
   // Do not edit RELEASE string: generated by 'make distr'

   public static final String RELEASE = "v2.0";

   // Application state.

   public static final int INIT_STATE = 0;
   public static final int CLEARED_STATE = 1;
   public static final int CANDIDATES_IMPORTED_STATE = 2;
   public static final int VOTES_IMPORTED_STATE = 3;
   public static final int PRIVATE_KEY_IMPORTED_STATE = 4;
   public static final int PUBLIC_KEY_IMPORTED_STATE = 5;
   public static final int VOTES_DECRYPTED_STATE = 6;
   public static final int VOTES_COUNTED_STATE = 7;
   public static final int REPORT_GENERATED_STATE = 8;

   // Messages.

   static final String TITLE = "Kiezen Op Afstand (" + RELEASE + ")";

   public static final String RESTART_BUT_TXT = "Restart";
   public static final String CLEAR_BUT_TXT = "Clear";
   public static final String IMPORT_CANDIDATES_BUT_TXT = "Import Candidates";
   public static final String IMPORT_VOTES_BUT_TXT = "Import Votes";
   public static final String IMPORT_PRIVATE_KEY_BUT_TXT = "Import Private Key";
   public static final String IMPORT_PUBLIC_KEY_BUT_TXT = "Import Public Key";
   public static final String DECRYPT_BUT_TXT = "Decrypt";
   public static final String COUNT_BUT_TXT = "Count";
   public static final String REPORT_BUT_TXT = "Report";
   public static final String HELP_BUT_TXT = "Help";
   public static final String EXIT_BUT_TXT = "Exit";

   static final String RESTART_TASK_MSG = "Restart...";
   static final String RESTART_WARNING_MSG = "Restart.\nAre you sure?";
   static final String RESTART_SUCCESS_MSG = "Restart successful!";
   static final String RESTART_FAILURE_MSG = "Restart failed!";

   static final String CLEAR_TASK_MSG = "Clear...";
   static final String CLEAR_WARNING_MSG_1 = "Clear.";
   static final String CLEAR_WARNING_MSG_2 = "Are you sure?";
   static final String CLEAR_WARNING_MSG = CLEAR_WARNING_MSG_1 + "\n" +
                                           CLEAR_WARNING_MSG_2;
   static final String CLEAR_SUCCESS_MSG = "Clear successful!";
   static final String CLEAR_FAILURE_MSG = "Clear failed!";

   static final String IMPORT_CANDIDATES_TASK_MSG = "Candidate Import...";
   static final String IMPORT_CANDIDATES_WARNING_MSG = "Candidate Import.\nAre you sure?";
   static final String IMPORT_CANDIDATES_SUCCESS_MSG = "Import successful!";
   static final String IMPORT_CANDIDATES_FAILURE_MSG = "Import failed!";

   static final String IMPORT_VOTES_TASK_MSG = "Import Votes...";
   static final String IMPORT_VOTES_WARNING_MSG = "Import Votes.\nAre you sure?";
   static final String IMPORT_VOTES_SUCCESS_MSG = "Votes imported successfuly!";
   static final String IMPORT_VOTES_FAILURE_MSG = "Failed to import votes!";

   static final String IMPORT_PUBLIC_KEY_TASK_MSG = "Public Key Import...";
   static final String IMPORT_PRIVATE_KEY_TASK_MSG = "Private Key Import...";
   // static final String IMPORT_KEY_TASK_MSG = "Sleutel Import...";
   static final String IMPORT_KEY_WARNING_MSG = "Key Import.\nAre you sure?";
   static final String IMPORT_KEY_SUCCESS_MSG = "Key Import successful!";
   static final String IMPORT_KEY_FAILURE_MSG = "Key Import failed!";
   
   static final String DECRYPT_TASK_MSG = "Decrypting votes...";
   static final String DECRYPT_WARNING_MSG = "Decrypt Votes.\nAre you sure?";
   static final String DECRYPT_SUCCESS_MSG = "Decryption successful!";
   static final String DECRYPT_FAILURE_MSG = "Decryption failed!";
   static final String DECRYPT_ERROR_MSG = "Decryption error!";
   static final String DECRYPT_ERROR_TAG = "DECRYPTERROR";

   static final String COUNT_TASK_MSG = "Count votes...";
   static final String COUNT_WARNING_MSG = "Count votes.\nAre you sure?";
   static final String COUNT_SUCCESS_MSG = "Count finished!";
   static final String COUNT_FAILURE_MSG = "Count failed!";

   static final String REPORT_TASK_MSG = "Report...";
   static final String REPORT_WARNING_MSG = "Report.\nAre you sure?";
   static final String REPORT_SUCCESS_MSG = "Report is gelukt!";
   static final String REPORT_FAILURE_MSG = "Report is mislukt!";

   static final String HELP_TASK_MSG = "Help...";

   static final String EXIT_TASK_MSG = "Exit Program...";
   static final String EXIT_WARNING_MSG = "Exit Program.\nAre you sure?";
   static final String EXIT_SUCCESS_MSG = "Exit successful!";
   static final String EXIT_FAILURE_MSG = "Exit failed!";

   static final String DIALOG_ERROR_MSG = "Dialog error!";

   static final String TASK_CANCELED_MSG = "Task canceled!";
   static final String NO_ERRORS_MSG = "No errors!";
   static final String VOTES_IGNORED_SEE_MORE_INFO_MSG = " votes ignored, see more info!";

   static final String DEFAULT_VOTING_INTERVAL = "10 May 2004 9:00 - 10 June 2004 17:00";

   static final Object[] OK_OPTIONS = { "OK" };

   public static final String CANCEL = "Cancel";
   public static final String YES = "Yes";
   public static final String NO = "No";
   public static final String FORWARD = "Forward";
   public static final String BACK = "Back";
   public static final String MORE_INFO = "More Info";
   public static final String LESS_INFO = "Less Info";
   
   static final Object[] OK_CANCEL_OPTIONS = { "OK", CANCEL };
   static final Object[] YES_CANCEL_OPTIONS = { YES, CANCEL };
   static final Object[] YES_NO_OPTIONS = { YES, NO };
   static final Object[] FORWARD_BACK_OPTIONS = { FORWARD, BACK };
   static final Object[] OK_MOREINFO_OPTIONS = { "OK", MORE_INFO };
   static final Object[] OK_MOREINFO_CANCEL_OPTIONS = { "OK", MORE_INFO, CANCEL };
   static final Object[] FORWARD_MOREINFO_BACK_OPTIONS = { FORWARD, MORE_INFO, BACK };
   static final Object[] OK_LESSINFO_OPTIONS = { "OK", LESS_INFO };
   static final Object[] OK_LESSINFO_CANCEL_OPTIONS = { "OK", LESS_INFO, CANCEL };
   static final int MOREINFO_OPTION = 1;
   static final int LESSINFO_OPTION = 1;

   static final Object[] REPORT_OPTIONS = { "Verwerkingsverslag", "Resultaat stemming", CANCEL };
   static final int AUDITLOG = 0;
   static final int RECOUNT = 1;

   // Files

   static final String TEMPDIR = System.getProperties().getProperty("java.io.tmpdir",".");
   static final String BASEDIR = System.getProperties().getProperty("user.home",TEMPDIR);
   static final String OUTDIR = "koa_out";

   static final String DECRYPTEDFILE = "decrypted.txt";

   static final String AUDITLOG_XSL = "xml/xslt/auditlog2pdf.xsl";
   static final String AUDITLOG_XML = "verwerkingsverslag.xml";
   static final String AUDITLOG_PDF = "verwerkingsverslag.pdf";

   static final String RECOUNT_XSL = "xml/xslt/recount2pdf.xsl";
   static final String RECOUNT_XML = "telling.xml";
   static final String RECOUNT_PDF = "telling.pdf";

   // Keytypes

   public static final int PUBLIC_KEYTYPE = 0;
   public static final int PRIVATE_KEYTYPE = 1;

   // Other constants
   public static final int NUMBER_OF_REDUNDANT_FIELDS = 7;
   public static final int MAX_KEY_LENGTH = 1024;
   public static final int MAX_ENCRYPTED_VOTE_LENGTH = 1024;
   public static final int ADDITIONAL_INFO_MAX_HEIGHT = 30;
   public static final int ADDITIONAL_INFO_MAX_WIDTH = 30;
   public static final int ADDITIONAL_INFO_EXTRA = 5;
   
}


